- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Install sshd components
  package:
    state: present
    name: ssh-server

- name: Backup default configurations
  command: "{{item}} > {{item}}.backup"
  with_items:
    - "{{ sshd_config }}"
    - "{{ ssh_moduli_config }}"

- name: Remove weak moduli from RSA
  command: |
  "awk '$5 >= 3071' {{ssh_moduli_config}}.backup > {{ssh_moduli_config}}"

- name: Provide hardened sshd_config
  copy:
    src: "{{module_path}}/files/sshd_config"
    dest: "{{sshd_config_path}}/sshd_config"
    owner: root
    group: root
    mode: 0600

- name: Allow by ip list 
  linefile:
    state: present
    insertafter: EOF
    line: "AllowUsers {{allow_user_ip_list}}"
  when: allow_user_ip_list | length > 0

- name: Allow by user name list 
  linefile:
    state: present
    insertafter: EOF
    line: | 
      "Match User {{allow_user_name_list.username}}
      AllowUsers {{allow_user_name_list.ip}}"
  with_items:
    - "{{restrict_user_list}}"
  when: restrict_user_list | length > 0