logrotate_config: /etc/logrotate.d/audispd
auditd_confdir: /etc/audit/rules.d
audisp_dir: /etc/rsyslog.d

audisp_syslog_target: /var/log/audispd/audispd.log
audisp_syslog_enable: true
osquery_process_auditing: false
#audisp_syslog_target: @@remotesyslog

#Fill auditd.conf
auditd_home: /etc/audit
auditd_disp_home: /etc/audisp
auditd_disp_syslog_active: 'no'
auditd_log_file: /var/log/audit/audit.log
auditd_log_format: raw
auditd_log_group: root
auditd_priority_boost: 4
auditd_flush: incremental
auditd_frequency: 20
auditd_num_logs: 5
auditd_disp_qos: lossy #lossless avoid 'dispatch err (pipe full) event lost' # auditd.conf(5)
auditd_dispatcher: /sbin/audispd
auditd_name_format: NONE
auditd_max_log_file: 20
auditd_max_log_file_action: rotate
auditd_space_left: 200
auditd_space_left_action: email
auditd_action_mail_acct: root
auditd_admin_space_left: 80
auditd_admin_space_left_action: single
auditd_disk_full_action: suspend
auditd_disk_error_action: suspend
auditd_tcp_listen_queue: 5
auditd_tcp_max_per_addr: 1
auditd_tcp_client_max_idle: 0
auditd_enable_krb5: 'no'
auditd_krb5_principal: auditd

# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security_guide/sec-audit_record_types
auditd_rules:
  - '-a always,exclude -F msgtype=CWD'
  - '-a always,exclude -F msgtype=EOE'
#  - '-a always,exclude -F msgtype=PATH'
  - '-a always,exclude -F msgtype=CRYPTO_KEY_USER'
# cron jobs
  - '-a never,user -F subj_type=crond_t'
# VMWare tools
#  - '-a exit,never -F arch=b32 -S fork -F success=0 -F path=/usr/lib/vmware-tools -F subj_type=initrc_t -F exit=-2'
#  - '-a exit,never -F arch=b64 -S fork -F success=0 -F path=/usr/lib/vmware-tools -F subj_type=initrc_t -F exit=-2'
#  - '-a exit,never -F dir=/var/lock/lvm'

#custom
#  - '-a exit,never -F dir=/path/to/directory'
#  - '-a exit,never -F path=/path/to/file'
#  - '-a exit,never -F auid=<UID>'

# uncommon_syscall
  - '-a exit,never -F arch=b64 -S prctl -F exe=/usr/sbin/sshd'
  - '-a exit,never -F arch=b64 -S prctl -F exe=/lib/systemd/systemd-journald'
  - '-a exit,never -F arch=b64 -S prctl -F exe=/lib/systemd/systemd-udevd'
  - '-a exit,never -F arch=b64 -S prctl -F exe=/bin/systemctl'
# admin_user_home
  - '-a exit,never -F arch=b64 -F dir=/home/ -F uid=0 -F auid=4294967295 -S lstat -F exe=/sbin/cgrulesengd'
  - '-a exit,never -F arch=b64 -F dir=/home/ -F uid=0 -F auid=4294967295 -S lstat -S stat -S open -S inotify_add_watch
        -S openat -S newfstatat -F exe=/usr/bin/osqueryd'
# unauthfileacess: setroubleshoot
  - '-a exit,never -F arch=b64 -S open -F success=0 -F uid=996 -F auid=4294967295 -F exe=/usr/bin/rpm'
  - '-a exit,never -F arch=b64 -S open -F success=0 -F uid=104 -F auid=4294967295 -F exe=/usr/sbin/rsyslogd -F dir=/var/log'
# specialfiles
  - '-a exit,never -F arch=b64 -S mknod -F success=0 -F uid=996 -F auid=4294967295
        -F exe=/usr/lib/systemd/systemd-logind'
# etcpasswd
  - '-a exit,never -F arch=b64 -F path=/etc/shadow -F uid=0 -F auid=4294967295 -S open -F exe=/usr/sbin/crond'
  - '-a exit,never -F arch=b64 -F path=/etc/shadow -F uid=0 -F auid=4294967295 -S open -F exe=/usr/sbin/sshd'
  - '-a exit,never -F arch=b64 -F path=/etc/shadow -F uid=0 -F auid=4294967295 -S open -F exe=/usr/sbin/unix_chkpwd'
# etcwrite
  - '-a exit,never -F arch=b64 -F dir=/etc/ -F uid=0 -F auid=4294967295 -S open -S rename -F exe=/usr/bin/osqueryd'
# Sensitive files
  - '-a exit,never -F arch=b64 -F uid=0 -F auid=4294967295 -S execve -F exe=/usr/sbin/sshd'
  - '-a exit,never -F arch=b64 -F uid=0 -F auid=4294967295 -S execve -F exe=/usr/lib64/sa/sadc'
  - '-a exit,never -F arch=b64 -F uid=0 -F auid=4294967295 -S execve -F exe=/usr/libexec/abrt-handle-event'
  - '-w /etc/group -p wa -k identity'
  - '-w /etc/gshadow -p wa -k identity'
  - '-w /etc/hosts -p wa -k system-locale'
  - '-w /etc/issue -p wa -k system-locale'
  - '-w /etc/issue.net -p wa -k system-locale'
  - '-w /etc/localtime -p wa -k time-change'
  - '-w /etc/passwd -p wa -k identity'
  - '-w /etc/security/opasswd -p wa -k identity'
  - '-w /etc/selinux/ -p wa -k MAC-policy'
  - '-w /etc/sudoers -p wa -k scope'
  - '-w /etc/sysconfig/network -p wa -k system-locale'
  - '-w /sbin/insmod -p x -k modules'
  - '-w /sbin/modprobe -p x -k modules'
  - '-w /sbin/rmmod -p x -k modules'
  - '-w /usr/sbin/insmod -p x -k modules'
  - '-w /usr/sbin/modprobe -p x -k modules'
  - '-w /usr/sbin/rmmod -p x -k modules'
